name: "Ruby"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      RAILS_ENV: test
      RUBYOPT: '-W:deprecated'
      FIREBASE_EMULATORS_PATH: ${{ github.workspace }}/emulator-cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          bundler-cache: true

      # https://dev.to/wceolin/caching-the-firebase-emulator-on-github-actions-4056
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ${{ env.FIREBASE_EMULATORS_PATH }}
          key:
            ${{ runner.os }}-firebase-emulators-${{
            hashFiles('emulator-cache/**') }}
        continue-on-error: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Firebase tools
        run: npm install -g firebase-tools

      - name: Run tests
        run: firebase emulators:exec bin/test --only firestore
